import { useState } from "react";
import jsPDF from "jspdf";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import type { Software, Shortcut } from "@/lib/types";

interface LeadMagnetProps {
  software: Software;
}

const generatePdf = (software: Software) => {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const W = doc.internal.pageSize.getWidth();
  let y = 60;

  // Header
  doc.setFillColor(255, 77, 0);
  doc.rect(0, 0, W, 8, "F");
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(`${software.name} — Shortcut Cheat Sheet`, 40, y);
  y += 24;
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by SoftwareOS · softwaros.lovable.app", 40, y);
  y += 24;

  const drawSection = (title: string, list: Shortcut[]) => {
    if (!list || list.length === 0) return;
    if (y > 700) { doc.addPage(); y = 60; }
    doc.setFontSize(14);
    doc.setTextColor(255, 77, 0);
    doc.setFont("helvetica", "bold");
    doc.text(title, 40, y);
    y += 18;
    doc.setFontSize(10);
    doc.setTextColor(40);
    doc.setFont("helvetica", "normal");
    list.forEach((s) => {
      if (y > 750) { doc.addPage(); y = 60; }
      doc.setFont("helvetica", "normal");
      doc.text(s.action.substring(0, 60), 40, y);
      doc.setFont("courier", "bold");
      doc.text(s.keys, W - 40, y, { align: "right" });
      y += 16;
    });
    y += 12;
  };

  const shortcuts = software.shortcuts && !Array.isArray(software.shortcuts) ? software.shortcuts : null;
  drawSection("Windows", shortcuts?.windows ?? []);
  drawSection("macOS", shortcuts?.mac ?? []);
  drawSection("iPhone", shortcuts?.iphone ?? []);
  drawSection("Android", shortcuts?.android ?? []);

  doc.save(`${software.slug}-shortcuts.pdf`);
};

export const LeadMagnet = ({ software }: LeadMagnetProps) => {
  const [email, setEmail] = useState("");
  const [busy, setBusy] = useState(false);
  const [done, setDone] = useState(false);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !/^\S+@\S+\.\S+$/.test(email)) {
      toast({ title: "Invalid email", description: "Enter a valid email.", variant: "destructive" });
      return;
    }
    setBusy(true);
    const { error } = await supabase.from("leads").insert({
      email,
      software_slug: software.slug,
      source: "pdf_cheatsheet",
    });
    if (error) {
      toast({ title: "Could not save", description: error.message, variant: "destructive" });
      setBusy(false);
      return;
    }
    try {
      generatePdf(software);
      setDone(true);
      toast({ title: "Sent!", description: `${software.name} cheat sheet downloaded.` });
    } catch (err) {
      toast({ title: "PDF error", description: String(err), variant: "destructive" });
    }
    setBusy(false);
  };

  return (
    <div className="glass p-6 my-10 reveal">
      <div className="flex items-start gap-4 flex-wrap">
        <div className="text-4xl">📄</div>
        <div className="flex-1 min-w-[220px]">
          <h3 className="text-lg font-bold gradient-text">
            Get the {software.name} cheat sheet (PDF)
          </h3>
          <p className="text-sm text-muted-foreground mt-1">
            Every shortcut on one printable page. We'll email it and download instantly.
          </p>
        </div>
        {done ? (
          <div className="text-sm font-mono text-primary">✓ check your inbox</div>
        ) : (
          <form onSubmit={submit} className="flex gap-2 flex-1 min-w-[260px]">
            <input
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@work.com"
              className="flex-1 h-10 px-3 rounded bg-card border border-border text-sm font-mono focus:outline-none focus:border-primary"
            />
            <button
              type="submit"
              disabled={busy}
              className="h-10 px-4 rounded bg-gradient-to-r from-primary to-primary-glow text-primary-foreground font-mono text-xs font-bold hover:shadow-glow transition disabled:opacity-50"
            >
              {busy ? "sending…" : "get pdf →"}
            </button>
          </form>
        )}
      </div>
    </div>
  );
};
